### ISSUE TITLE
equations in L46-L55

### ISSUE THREAD

**Issue by kongdd** [anj1/ThinPlateSplines.jl#2]
Dear @anj1 and @lootie, 

I have read the document of Thin Plate Spline carefully in wikipedia throughly.  But I am still unable to figure out which equations used in L46-L55 (https://github.com/anj1/ThinPlateSplines.jl/blob/master/src/ThinPlateSplines.jl#L46). Could you give some clue or some references? 

Thanks for your awesome work. Wish to hear from you. 

Cheers,
Dongdong

**Comment by anj1** [comment]
`tps_solve` finds the solution (d,c) that minimizes the energy E_tps. The energy minimization is just a least-squares minimization problem. The wiki page doesn't give a method for finding the minimum. QR factorization is a well-known method for solving least-squares problems.
Let me know if you have further questions.

**Comment by kongdd** [comment]
Sorry, although know it is QR, but still can't figure out why. Could you give some deduction?
Thank you very much!

**Comment by kongdd** [comment]
The following is my unfinished deduction, could you give some clue how to use QR decompose?
Thank you!

![image](https://user-images.githubusercontent.com/9815742/126925004-7b0cfc8f-6716-4ce3-8299-020ce0d44bca.png)

**Comment by anj1** [comment]
See https://en.wikipedia.org/wiki/Regularized_least_squares
and https://math.stackexchange.com/questions/2013160/qr-factorization-regularized-least-squares

**Comment by kongdd** [comment]
thank you

**Comment by kongdd** [comment]
I found this thesis deduce those equations clearly, in P18-19, Eq. 3.6 and 3.7. I suggest adding it as reference. 
https://research.tue.nl/files/46994318/692226-1.pdf
Thanks for your awesome work.
