### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by RainerHeintzmann** [anj1/ThinPlateSplines.jl#4]
Are you thinking about making a release? It would be good, since others may want to release a package that may depend on this great `ThinPlateSpline.jl` package and it may also be much easier to find within the Julia `REPL`.

**Comment by RainerHeintzmann** [comment]
Hi @anj1 . Thanks a lot for merging the pull request. It would be really cool, if this package can also be released.
Is there a particular reason to not release it? Do you need any help with releasing it?

**Comment by anj1** [comment]
No reason not to release, just wasn't a priority before. It's probably ready for release now, will have a look at doing that.

**Comment by RainerHeintzmann** [comment]
This would be great! Thanks!

**Comment by RainerHeintzmann** [comment]
.. just make sure that the version number in the Project.toml is 0.1.0 and
comment on the latest commit with
@JuliaRegistrator register
Then everything should be happening automatically. You may want to first install 
[Julia TagBot GitHub Action](https://github.com/marketplace/actions/julia-tagbot)
which saves you some work with the versioning.

**Comment by anj1** [comment]
I get this error from Registrator:

```
The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: Tullio
```
Since Tullio was introduced in https://github.com/anj1/ThinPlateSplines.jl/pull/5, can you provide this compat entry, thanks.

**Comment by RainerHeintzmann** [comment]
Yes. Sorry. You should also add 1.9 in the julia tag (I did a test with 1.9.2).
Since I only tested with Tullio 0.3.5, I suggest we add the following lines:
[compat]
julia = "1, 1.6, 1.7, 1.8, 1.9"
Tullio = "0.3"

I also tested this and it seems to be fine. I think the easiest is, if you just replace the current entry with this.
Thanks!
